import { NextResponse } from "next/server";
import { courses } from "@/lib/mock-data";
import { scoreQuiz } from "@/lib/eduflow";

export async function POST(request: Request) {
  const contentType = request.headers.get("content-type") ?? "";
  const payload = contentType.includes("application/json")
    ? await request.json()
    : Object.fromEntries((await request.formData()).entries());
  const quizId = String(payload.quizId ?? "");
  const quiz = courses.flatMap((course) => course.quizzes).find((item) => item.id === quizId);

  if (!quiz) {
    return NextResponse.json({ error: "Quiz not found" }, { status: 404 });
  }

  const answers = Object.fromEntries(
    quiz.questions.map((question) => [question.id, String(payload[question.id] ?? "")]),
  );

  return NextResponse.json({
    quizId,
    ...scoreQuiz(quiz, answers),
    feedback: "Instant feedback generated by the quiz service.",
  });
}
