import { NextResponse } from "next/server";
import { courses } from "@/lib/mock-data";
import { scoreQuiz } from "@/lib/eduflow";

export async function POST(request: Request) {
  const contentType = request.headers.get("content-type") ?? "";
  const payload = contentType.includes("application/json")
    ? await request.json()
    : Object.fromEntries((await request.formData()).entries());
  const quizId = String(payload.quizId ?? "");
  const courseId = String(payload.courseId ?? "");
  const lessonId = String(payload.lessonId ?? "");
  const quiz = courses.flatMap((course) => course.quizzes).find((item) => item.id === quizId);

  if (!quiz) {
    return NextResponse.json({ error: "Quiz not found" }, { status: 404 });
  }

  const answers = Object.fromEntries(
    quiz.questions.map((question) => [question.id, String(payload[question.id] ?? "")]),
  );
  const result = scoreQuiz(quiz, answers);

  if (!contentType.includes("application/json")) {
    const notice = result.passed ? "quiz-passed" : "quiz-review";
    return NextResponse.redirect(
      new URL(`/learn/${courseId}/${lessonId}?notice=${notice}`, request.url),
      303,
    );
  }

  return NextResponse.json({
    quizId,
    ...result,
    feedback: "Instant feedback generated by the quiz service.",
  });
}
